apiVersion: v1
kind: Pod
metadata:
  name: reactui-app
spec:
  containers:
  - name: ui
    image: cloudytuts.com/reactui-demo
    env:
      - name: PLAYER_INITIAL_LIVES
        valueFrom:
          configMapKeyRef:
            name: game-demo
            key: player_initial_lives
      - name: UI_PROPERTIES_FILE_NAME
        valueFrom:
          configMapKeyRef:
            name: game-demo
            key: ui_properties_file_name
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: game-demo-secrets
            key: db.user
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: game-demo-secrets
            key: db.password