apiVersion: apps/v1
kind: Deployment
metadata:
  name: jekyll-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jekyll-website
  template:
    metadata:
      labels:
        app: jekyll-website
    spec:
      containers:
      - name: website
        image: jekyll-website:1.0.0
        ports:
          - containerPort: 80
        livenessProbe:
            httpGet:
                path: /
                port: 80
                httpHeaders:
                    - name: Custom-Header
                      value: healthcheck
            initialDelaySeconds: 3
            periodSeconds: 3
