apiVersion: v1
kind: ConfigMap
metadata:
    name: reactui-config
data:
    player_lives: 3
    ui_properties: "user-interface.properties"
    game.properties: |
        enemy.types=aliens,monsters
        player.maximum-lives=5
    user-interface.properties: |
        color.good=purple
        color.bad=yellow
        allow.textmode=true