# DO NOT store sensitive values in a version control system. Values in this
# manifest are here for demonstration purposes only. 
apiVersion: v1
kind: Secret
metadata:
  name: postgres
data:
  POSTGRES_PASSWORD: bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk
stringData:
  POSTGRES_USER: root